@extends('dashboard.layouts.app')

@section('page-title', 'Dashboard')

@section('content')

    {{-- ===== SUMMARY CARDS ===== --}}
    {{--
    Data from DashboardController:
    $totalIncome, $totalExpense, $netBalance, $totalTransactions
    number_format() formats money with commas and 2 decimals
    --}}
    <div class="summary-cards">

        <div class="summary-card income">
            <div class="card-icon">
                <i class="fas fa-arrow-trend-up"></i>
            </div>
            <div class="card-content">
                <p class="card-label">Total Income</p>
                <h3 class="card-amount">
                    NPR {{ number_format($totalIncome, 2) }}
                </h3>
            </div>
        </div>

        <div class="summary-card expense">
            <div class="card-icon">
                <i class="fas fa-arrow-trend-down"></i>
            </div>
            <div class="card-content">
                <p class="card-label">Total Expense</p>
                <h3 class="card-amount">
                    NPR {{ number_format($totalExpense, 2) }}
                </h3>
            </div>
        </div>

        <div class="summary-card balance">
            <div class="card-icon">
                <i class="fas fa-wallet"></i>
            </div>
            <div class="card-content">
                <p class="card-label">Net Balance</p>
                <h3 class="card-amount">
                    NPR {{ number_format($netBalance, 2) }}
                </h3>
            </div>
        </div>

        <div class="summary-card month">
            <div class="card-icon">
                <i class="fas fa-calendar"></i>
            </div>
            <div class="card-content">
                <p class="card-label">Transactions</p>
                <h3 class="card-amount">
                    {{ $totalTransactions }}
                </h3>
            </div>
        </div>

    </div>

    {{-- ===== CHARTS SECTION ===== --}}
    {{--
    Chart.js renders inside <canvas> tags
        Data passed via window object in @push('scripts')
        charts.js reads window.spendingData and window.monthlyData
        --}}
        <div class="charts-section">

            <div class="chart-placeholder">
                <h3 class="chart-title">
                    <i class="fas fa-chart-pie"></i>
                    Spending by Category
                </h3>
                <canvas id="pieChart"></canvas>
            </div>

            <div class="chart-placeholder">
                <h3 class="chart-title">
                    <i class="fas fa-chart-bar"></i>
                    Monthly Overview
                </h3>
                <canvas id="barChart"></canvas>
            </div>

        </div>

        {{-- ===== SMART INSIGHTS ===== --}}
        {{--
        $insights is an array of insight objects
        Each has: type, icon, message
        Generated by generateInsights() in DashboardController

        type → controls CSS class → controls color:
        success → green
        warning → yellow
        danger → red
        info → blue
        --}}
        <div class="insights-section">

            <div class="insights-title">
                <i class="fas fa-lightbulb"></i>
                Smart Insights — {{ now()->format('F Y') }}
            </div>

            <div class="insights-list">
                @foreach($insights as $insight)
                    {{--
                    Dynamic class — e.g. "insight-item success"
                    Dynamic icon — Font Awesome class from array
                    Dynamic message — insight text
                    --}}
                    <div class="insight-item {{ $insight['type'] }}">
                        <i class="{{ $insight['icon'] }} insight-icon"></i>
                        <span>{{ $insight['message'] }}</span>
                    </div>
                @endforeach
            </div>

        </div>

        {{-- ===== RECENT TRANSACTIONS ===== --}}
        {{--
        $recentTransactions — last 5 transactions
        limit(5) in controller — just a preview
        "View All" links to full transactions page
        --}}
        <div class="transactions-section">

            <div style="display:flex; justify-content:space-between;
                        align-items:center; margin-bottom:20px;">
                <h2 class="section-title" style="margin:0;">
                    Recent Transactions
                </h2>
                <a href="{{ route('transactions.index') }}" style="color:#6366f1; font-size:13px; font-weight:600;
                            text-decoration:none;">
                    View All →
                </a>
            </div>

            <div class="table-container">
                <table class="transactions-table">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Category</th>
                            <th>Note</th>
                            <th>Type</th>
                            <th>Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($recentTransactions as $transaction)
                            <tr>
                                {{-- Date --}}
                                <td>
                                    {{ $transaction->date->format('d M Y') }}
                                </td>

                                {{-- Category with color dot --}}
                                <td>
                                    <span class="category-badge">
                                        <span class="category-dot" style="background-color:{{ $transaction->category->color }}">
                                        </span>
                                        {{ $transaction->category->name }}
                                    </span>
                                </td>

                                {{-- Note — show dash if empty --}}
                                <td>{{ $transaction->note ?? '—' }}</td>

                                {{-- Type badge — income or expense --}}
                                <td>
                                    <span class="type-badge {{ $transaction->type }}">
                                        {{ ucfirst($transaction->type) }}
                                    </span>
                                </td>

                                {{-- Amount — green + for income, red - for expense --}}
                                <td>
                                    <span class="amount {{ $transaction->type }}">
                                        {{ $transaction->type == 'income' ? '+' : '-' }}
                                        NPR {{ number_format($transaction->amount, 2) }}
                                    </span>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="5">
                                    <div class="empty-state">
                                        <i class="fas fa-inbox"></i>
                                        <p>No transactions yet</p>
                                    </div>
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

        </div>

        @push('scripts')
            {{--
            Pass PHP data to charts.js via window object
            @json() converts PHP collection to JS array
            charts.js reads window.spendingData and window.monthlyData
            This runs AFTER charts.js loads — correct order
            --}}
            <script>
                window.spendingData = @json($spendingByCategory);
                window.monthlyData = @json($last6Months);
            </script>
        @endpush

@endsection